#!/bin/bash

if [ "$#" -ne 6 ]; then
    echo "Uso: $0 <comunidade> <ip> <index> <porta> <tipo_de_sinal> <tipo_de_lane>"
    echo "Exemplo: $0 DWTelecom 10.64.255.9 67518542 161 RX M"
    exit 1
fi

comunidade=$1
ip=$2
index=$3
porta=$4
tipo_de_sinal=$5
tipo_de_lane=$6

/opt/signaloptical/venv/bin/python3 /opt/signaloptical/signal_optical.py "$comunidade" "$ip" "$index" "$porta" "$tipo_de_sinal" "$tipo_de_lane"
