#!/bin/bash

if [ "$#" -lt 3 ]; then
    echo "Uso: $0 <comunidade> <porta> <ip_especifico1> [<ip_especifico2> ...]"
    exit 1
fi

comunidade=$1
porta=$2
shift 2
ips="$@"

# Substituir espaços por vírgulas e remover vírgulas extras
ips=$(echo $ips | sed 's/ /,/g' | sed 's/,,*/,/g')

/opt/asnname/venv/bin/python3 /opt/asnname/status_as.py "$comunidade" "$porta" "$ips"
